Create database QLyKhoHang 

select* from KHACHHANG
---/-/-/-/-//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-------------- TẠO BẢNG -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/ --------

CREATE TABLE NHOMNGUOIDUNG (
    IDNhom INT PRIMARY KEY,
    TenNhom NVARCHAR(100),
    Quyen NVARCHAR(255)
);

CREATE TABLE NGUOIDUNG (
    IDND INT PRIMARY KEY,
    TenND NVARCHAR(100),
    SDT VARCHAR(15),
    TenDN NVARCHAR(50),
    MatKhau VARCHAR(50),
    ChucVu NVARCHAR(50),
    IDNhom INT,
    CONSTRAINT FK_NguoiDung_Nhom FOREIGN KEY (IDNhom) 
    REFERENCES NHOMNGUOIDUNG(IDNhom)
);

-- ------------------------------------1. Nhóm danh mục --------------------
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH NVARCHAR(100),
    DiaChi NVARCHAR(200),
    Sdt VARCHAR(15),
    Stk VARCHAR(20)
);

CREATE TABLE XUONG (
    MaXuong VARCHAR(20) PRIMARY KEY,
    TenXuong NVARCHAR(100)
);

CREATE TABLE NGUYENLIEU (
    MaNL VARCHAR(20) PRIMARY KEY,
    TenNL NVARCHAR(100),
    DVT NVARCHAR(20),
    SoLg INT,
    Gia DECIMAL(18,2)
);

CREATE TABLE HANG (
    MaH VARCHAR(20) PRIMARY KEY,
    TenH NVARCHAR(100),
    SoLg INT,
    Gia DECIMAL(18,2),
    MaLH VARCHAR(20) FOREIGN KEY REFERENCES LOAIHANG(MaLH)
);

CREATE TABLE LOAIHANG (
    MaLH VARCHAR(20) PRIMARY KEY,
    TenLH NVARCHAR(100)
);

-----------------------------------2.Bảng phiếu và nghiệp vụ ---------------------------

CREATE TABLE PHIEUXUAT (
    MaPxuat VARCHAR(20) PRIMARY KEY,
    TenNgXuat NVARCHAR(100),
    Dv NVARCHAR(50),
    NgayXuat DATE
);

CREATE TABLE HOADON (
    MaHD VARCHAR(20) PRIMARY KEY,
    MaKH VARCHAR(20) FOREIGN KEY REFERENCES KHACHHANG(MaKH),
    NgayL DATE,
    MaPxuat VARCHAR(20) FOREIGN KEY REFERENCES PHIEUXUAT(MaPxuat),
    IDND INT,
	CONSTRAINT FK_HoaDon_NguoiDung FOREIGN KEY (IDND) 
    REFERENCES NGUOIDUNG(IDND)
);

CREATE TABLE PHIEUNHAP (
    MaPnhap VARCHAR(20) PRIMARY KEY,
    TenNgNhap NVARCHAR(100),
    Dv NVARCHAR(50),
    MaXuong VARCHAR(20) FOREIGN KEY REFERENCES XUONG(MaXuong),
    NgayNh DATE,
    MaNL VARCHAR(20) FOREIGN KEY REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE PHIEUDAT (
    MaPdat VARCHAR(20) PRIMARY KEY,
    TenNbgiao NVARCHAR(100),
    Dv NVARCHAR(50),
    NgayDat DATE,
    MaNL VARCHAR(20) FOREIGN KEY REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE PHIEUCHATLUONG (
    MaPCL VARCHAR(20) PRIMARY KEY,
    TenNKiem NVARCHAR(100),
    Dv NVARCHAR(50),
    MaXuong VARCHAR(20) FOREIGN KEY REFERENCES XUONG(MaXuong),
    NgayL DATE,
    MaNL VARCHAR(20) FOREIGN KEY REFERENCES NGUYENLIEU(MaNL)
);

-- ---------------------- ---3. CÁC BẢNG CHI TIẾT -----------------------------


CREATE TABLE DHOADON (
    MaHD VARCHAR(20) FOREIGN KEY REFERENCES HOADON(MaHD),
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    Gia DECIMAL(18,2),
    SoLg INT,
    PRIMARY KEY (MaHD, MaH)
);

CREATE TABLE DXUATKHO (
    MaPxuat VARCHAR(20) FOREIGN KEY REFERENCES PHIEUXUAT(MaPxuat),
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    Gia DECIMAL(18,2),
    SoLg INT,
    PRIMARY KEY (MaPxuat, MaH)
);

CREATE TABLE DNHAPKHO (
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    MaPnhap VARCHAR(20) FOREIGN KEY REFERENCES PHIEUNHAP(MaPnhap),
    Gia DECIMAL(18,2),
    SoLg INT,
    PRIMARY KEY (MaH, MaPnhap)
);

CREATE TABLE DDATGIACONG (
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    MaPdat VARCHAR(20) FOREIGN KEY REFERENCES PHIEUDAT(MaPdat),
    Giatri DECIMAL(18,2),
    Mota NVARCHAR(MAX),
    DTkythuat NVARCHAR(MAX),
    PRIMARY KEY (MaH, MaPdat)
);

CREATE TABLE DCHATLUONGH (
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    MaPCL VARCHAR(20) FOREIGN KEY REFERENCES PHIEUCHATLUONG(MaPCL),
    ChatLg NVARCHAR(50),
    Tinhtrang NVARCHAR(50),
    PRIMARY KEY (MaH, MaPCL)
);

CREATE TABLE NL_H (
    MaH VARCHAR(20) FOREIGN KEY REFERENCES HANG(MaH),
    MaNL VARCHAR(20) FOREIGN KEY REFERENCES NGUYENLIEU(MaNL),
    PRIMARY KEY (MaH, MaNL)
);