spring.application.name=QuanLyKho
# 1. k\u1EBFt n\u1ED1i sql sever
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QLyKhoHang;encrypt=true;trustServerCertificate=true

# 2. T\u00E0i kho\u1EA3n sever
spring.datasource.username=sa
spring.datasource.password=123456789

# 3. Driver cho SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate c\u1EADp n\u1EADt b\u1EA3ng d\u1EF1a tr\u00EAn entity
spring.jpa.hibernate.ddl-auto=update

# 5. hi\u1EC7n c\u00E2u l\u1EC7nh sql ra console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# C\u1EA5m Spring Boot t\u1EF1 \u00FD s\u1EEDa t\u00EAn b\u1EA3ng/c\u1ED9t (Gi\u1EEF nguy\u00EAn CamelCase v\u00E0 Vi\u1EBFt hoa)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl